---
- name: "Criando usuários para o prometheus"
  ansible.builtin.user:
    name: prometheus 
    state: present
    shell: /bin/false        

- name: "Criando usuários para o node exporter"
  user:
    name: node_exporter
    state: present
    shell: /bin/false
  
- name: "Criando diretorio em /etc/prometheus"
  file:
    path: /etc/prometheus
    state: directory

- name: "Criando diretorio em /var/lib/prometheus"
  file:
    path: /var/lib/prometheus
    state: directory 

- name: "Baixando o prometheus"
  get_url: 
    url: "https://github.com/prometheus/prometheus/releases/download/v2.31.1/prometheus-2.31.1.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar

- name: "Descompactando o prometheus"
  unarchive:
    src: /tmp/prometheus.tar
    dest: /tmp
    remote_src: yes

- name: "Copiando arquivos do prometheus para /usr/local/bin"
  copy:
    src: /tmp/prometheus*/prom*
    dest: /usr/local/bin/

- name: "Copiando arquivos do prometheus para /etc/prometheus"
  copy:
   src: /tmp/prometheus*/con*
   dest: /etc/prometheus

- name: "Tornando o usuário prometheus dono das pastas criadas"
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
  loop: 
  - /etc/prometheus
  - /var/lib/prometheus
  - /usr/local/bin/prom*
  
- name: "Copiando arquivo prometheus.service"
  template:
    src: ../templates/prometheus.service
    dest: /etc/systemd/system/prometheus.service

  notify: restart-prometheus