---
- name: "Criando usuários para o prometheus"
  ansible.builtin.user:
    name: "{{ item }}" 
    state: present
    shell: /bin/false  
  loop:
  - prometheus
  - node_exporter      
 
- name: "Criando diretorio para funcionamento do prometheus"
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - /var/lib/prometheus
  - /etc/prometheus
  - /tmp/prometheus # necessário para extrair o prometheus

- name: "Baixando o prometheus"
  get_url: 
    url: {{ prometheuslink }}
    dest: /tmp/prometheus.tar

- name: "Descompactando o prometheus"
  unarchive:
    src: /tmp/prometheus.tar
    dest: /tmp/prometheus
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: "Copiando arquivo prometheus para /usr/local/bin"
  copy:
    src: "{{ item }}" 
    dest: /usr/local/bin
    remote_src: yes 
  loop:   
  - /tmp/prometheus/prometheus
  - /tmp/prometheus/promtool

- name: "Copiando arquivo prometheus para /etc/prometheus"
  copy:
    src: "{{ item }}" 
    dest: /etc/prometheus
    remote_src: yes 
  loop:   
  - /tmp/prometheus/consoles
  - /tmp/prometheus/console_libraries

- name: "Tornando o usuário prometheus dono das pastas criadas"
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
  loop: 
  - /etc/prometheus
  - /var/lib/prometheus
  - /usr/local/bin/promtool
  - /usr/local/bin/prometheus
  
- name: "Copiando arquivo prometheus.service"
  template:
    src: ../templates/prometheus.service
    dest: /etc/systemd/system/prometheus.service

  notify: restart-prometheus